In [1]:
import sys
sys.path.append("../")

In [9]:
from config import cfg, cfg_from_file
import os
from data import MaterialLoader, EvalLoader
from pretrain import preTrainer
from evaluate import Evaluator

In [6]:
cfg.DEVICE = 'cuda:2'
cfg.FROM_PATH = True
cfg.CUT_DATA = False
cfg.DATASET_NAME = "mp_3d_2020_maxA20_N48840_CUT_3600"
cfg.TRAIN.max_epoch = 50
cfg.TRAIN.snapshot_interval = 5


In [7]:
'''
# Test condition

Formula CGConv
reparametrize at input stage
sg_nce_loss+=
lr 0.001
'''

In [8]:
train_loader , valid_loader, test_loader = MaterialLoader()
ptrainer = preTrainer(train_loader, valid_loader, test_loader)
ptrainer.train()

Load dataset
Loading from path, dataset name : mp_3d_2020_maxA20_N48840_CUT_3600
NUM TRAIN:3240, NUM VALID:180, NUM_TEST:180


100%|█████████▉| 299/300 [01:23<00:00,  3.58it/s]


graph building issue, 0 discarded from train data
## Start pre-training
Epoch 5/50  Train loss :12.6167  Valid loss:12.4460  Interval time elapsed: 0.0267
Train loss details
atom feat recon loss:0.28  adj recon loss:1.07  space group loss:4.58  space group contrastive loss:3.16  2d 3d contrastive loss:  2.60  input kld loss:  29.05 source target embedding diff loss :0.64
Epoch 10/50  Train loss :11.3333  Valid loss:11.4541  Interval time elapsed: 0.0535
Train loss details
atom feat recon loss:0.25  adj recon loss:0.97  space group loss:4.12  space group contrastive loss:2.76  2d 3d contrastive loss:  2.36  input kld loss:  26.89 source target embedding diff loss :0.61
Epoch 15/50  Train loss :10.6273  Valid loss:11.1819  Interval time elapsed: 0.0802
Train loss details
atom feat recon loss:0.23  adj recon loss:0.86  space group loss:3.90  space group contrastive loss:2.67  2d 3d contrastive loss:  2.10  input kld loss:  27.63 source target embedding diff loss :0.60
Epoch 20/50  Train l

In [42]:
import torch
import torch.nn as nn
oo = torch.ones(2,5)
lin = nn.Linear(5,3)
lin(oo)


tensor([[-0.6833, -0.8699,  0.6895],
        [-0.6833, -0.8699,  0.6895]], grad_fn=<AddmmBackward0>)

In [49]:
bb = torch.randn(5,3)

In [50]:
oo

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [51]:
bb

tensor([[ 0.6427,  0.6639, -0.5135],
        [-0.2638,  1.1413,  0.3218],
        [-0.5501,  0.2651,  0.1670],
        [ 0.4163, -2.3609, -0.9746],
        [ 2.2786,  0.2211, -1.0350]])

In [53]:
oo@bb

tensor([[ 2.5237, -0.0694, -2.0344],
        [ 2.5237, -0.0694, -2.0344]])

In [55]:
bb.sum(dim=0)

tensor([ 2.5237, -0.0694, -2.0344])

In [94]:
inp = torch.ones(10,2,5)
www = torch.randn(10, 5,2)
out = torch.matmul(inp, www)
out.shape

torch.Size([10, 2, 2])

In [95]:
out.mean(dim = 1).T.shape

torch.Size([2, 10])

In [96]:
out

tensor([[[ 0.9176,  0.8993],
         [ 0.9176,  0.8993]],

        [[-1.5300, -0.9391],
         [-1.5300, -0.9391]],

        [[ 7.6285,  0.7230],
         [ 7.6285,  0.7230]],

        [[ 1.3110,  2.5624],
         [ 1.3110,  2.5624]],

        [[ 0.5787,  1.2655],
         [ 0.5787,  1.2655]],

        [[ 3.0386,  2.8315],
         [ 3.0386,  2.8315]],

        [[-0.7460,  1.3690],
         [-0.7460,  1.3690]],

        [[ 0.1284, -0.5964],
         [ 0.1284, -0.5964]],

        [[ 2.9800, -3.0482],
         [ 2.9800, -3.0482]],

        [[ 3.8682,  1.2729],
         [ 3.8682,  1.2729]]])

In [99]:
inx = out.mean(dim=1).T

In [100]:
inx.shape

torch.Size([2, 10])

In [102]:
lin_out = nn.Linear(10,1)
lin_out(inx).shape

torch.Size([2, 1])

In [103]:
lin_out(inx)

tensor([[2.9537],
        [0.1196]], grad_fn=<AddmmBackward0>)

In [104]:
inp

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [107]:
inx.mean(dim=-1)

tensor([1.8175, 0.6340])

In [134]:
data

DataBatch(y=[256, 1], y_batch=[256], y_ptr=[257], node_features_s=[1127, 92], atom_types_s=[1127], edge_index_s=[2, 6521], atom_weights_s=[6521, 1], batch=[1127], ptr=[257])

In [31]:
cfg.EVAL.dataset = "oqmd-form-enthalpy.csv"
cfg.EVAL.max_epoch = 20
cfg.EVAL.snapshot_inverval = 5

In [32]:
_train_loader, _valid_loader, _test_loader = EvalLoader()
load_pth = os.path.join(cfg.CHECKPOINT_DIR, "pretrain_0307_3600")

Loading Eval dataset: oqmd-form-enthalpy.csv
NUM TRAIN:230959, NUM VALID:12831, NUM_TEST:12832


100%|█████████▉| 21384/21385 [00:05<00:00, 4074.80it/s]


In [33]:
cfg.WEIGHTS = "finetune"
evaluator = Evaluator(_train_loader, _valid_loader, _test_loader, load_pth)
evaluator.train()

## Start linear evaluation (weights:finetune, target property:formation_energy_per_atom)


/home/isota/workspace/conda_envs/gfinfomax/lib/python3.9/site-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([256, 1])) that is different to the input size (torch.Size([255, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


RuntimeError: The size of tensor a (255) must match the size of tensor b (256) at non-singleton dimension 0

In [ ]:
cfg.WEIGHTS = "freeze"
evaluator = Evaluator(_train_loader, _valid_loader, _test_loader, load_pth)
evaluator.train()

In [ ]:
cfg.WEIGHTS = "rand_init"
evaluator = Evaluator(_train_loader, _valid_loader, _test_loader, load_pth)
evaluator.train()

In [ ]:
data = next(iter(_train_loader))
data = data.to(cfg.DEVICE)
out = evaluator.decoder(data)
print(out.shape)
print(data.y.shape)
print(data)
# batch is missing, last time same issue, check spread graph

from torch_geometric.nn import global_add_pool
a = global_add_pool(data.node_features_s, data.batch)
print(a.shape)
data.batch